# Generated by Django 4.2.7 on 2024-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='capacity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_rooms',
            field=models.IntegerField(blank=True),
        ),
    ]
