# Generated by Django 4.2.7 on 2024-01-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_offer_address2_alter_offer_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
