# Generated by Django 4.2.7 on 2024-01-28 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_offer_capacity_alter_offer_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
