# Generated by Django 4.2.7 on 2024-01-28 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
