# Generated by Django 4.2.7 on 2024-01-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='opinion',
        ),
        migrations.AddField(
            model_name='reservation',
            name='offert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.offer'),
        ),
    ]
